name       : libxfont
version    : 1.5.3
release    : 10
source     :
    - https://www.x.org/releases/individual/lib/libXfont-1.5.3.tar.gz : e8e3538dacf0a3c0317f0b92a092a3bd9d70fd23de10a6d895435ac78de54b7c
license    : MIT
component  : xorg.library
summary    : X11 font rasterisation library
description: |
    libXfont provides various services for X servers, most notably font selection and rasterisation (through external libraries).
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig(fontsproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xtrans)
    - pkgconfig32(fontenc)
    - pkgconfig32(freetype2)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
