name       : libxfont
version    : 1.5.2
release    : 9
source     :
    - https://www.x.org/releases/individual/lib/libXfont-1.5.2.tar.gz : a7350c75171d03d06ae0d623e42240356d6d3e1ac7dfe606639bf20f0d653c93
license    :
    - MIT
summary    : X11 font rasterisation library
component  : xorg.library
builddeps  :
    - pkgconfig(fontsproto)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xtrans)
    - pkgconfig(fontenc)
    - pkgconfig32(fontenc)
    - pkgconfig32(zlib)
    - pkgconfig32(freetype2)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
description: |
    libXfont provides various services for X servers, most notably font selection and rasterisation (through external libraries).
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
