name       : libxfont
version    : 1.5.4
release    : 14
source     :
    - https://www.x.org/releases/individual/lib/libXfont-1.5.4.tar.gz : 59be6eab53f7b0feb6b7933c11d67d076ae2c0fd8921229c703fc7a4e9a80d6e
license    : MIT
component  : xorg.library
summary    : X11 font rasterisation library
description: |
    libXfont provides various services for X servers, most notably font selection and rasterisation (through external libraries).
emul32     : yes
optimize   :
    - speed
builddeps  :
    - pkgconfig(fontsproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xtrans)
    - pkgconfig32(fontenc)
    - pkgconfig32(freetype2)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
setup      : |
    unset LDFLAGS
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
